### ISSUE TITLE
CDN Error

### ISSUE THREAD

**Issue by velopeloton** [xbgmsharp/piwigo-cdnplus#1]
When I try to enable the cdn I get the following error
"CDN enable but no CDN domain setup or Site Root define"
The site root is unedited and I have entered in my cdn details.

**Comment by xbgmsharp** [comment]
You more likely did not define the root field. be default you should set it to ``/``

**Comment by velopeloton** [comment]
Doh! Thank you.

**Comment by xbgmsharp** [comment]
No worries, you might want to check the wiki documentation.
https://github.com/xbgmsharp/piwigo-cdnplus/wiki#admin-panel
