### ISSUE TITLE
how to solve error "CDN enable but no CDN domain setup or Site Root define"

### ISSUE THREAD

**Issue by oradio** [xbgmsharp/piwigo-cdnplus#10]
Hi, I installed CDNPlus on Piwigo 2.9.2 but when I tried to fill in my CDN domain and save it, en error showed up like this:

CDN enable but no CDN domain setup or Site Root define

Can you help me solve the problem? thank you!

![screenshot2017-10-23 23-43-37-500](https://user-images.githubusercontent.com/2052700/31898638-1d176e56-b84c-11e7-9d8b-a657a5f6fa2d.jpeg)

**Comment by oradio** [comment]
found out that it was because I did not type "/" in the site root field...

**Comment by benjaminchodroff** [comment]
I hit the same issue. There should be a default of "/" provided - small usability issue but it was quite frustrating!
